default-resources:
  mem: "10G"
  cpus_per_task: 1
cores: 8
printshellcmds: True
latency-wait: 100
rerun-triggers:
  - mtime

config:
  REF_DIR: "/mnt/isilon/zhou_lab/projects/20191221_references/"
  BBDUK: "bbduk.sh"
  PYTHON: "/mnt/isilon/zhoulab/labsoftware/anaconda/conda_2026/bin/python"
