executor: cluster-generic
cluster-generic-submit-cmd:
  "mkdir -p logs/{rule} &&
    sbatch
    --time={resources.time}
    --mem={resources.mem_mb}
    --cpus-per-task={resources.cpus_per_task}
    --job-name=smk-{rule}-%j
    --output=logs/{rule}/{rule}-%j.out
    --error=logs/{rule}/{rule}-%j.err"
default-resources:
  - time="01:00:00"
  - mem="10G"
  - cpus_per_task=1

configfile:
  - profiles/slurm/site.yaml

jobs: 100
printshellcmds: True
latency-wait: 100
rerun-triggers:
  - mtime
