# Snakemake CLI Flags (Behavior)
cluster:
  "mkdir -p logs/{rule} &&
    sbatch
    --time={resources.time}
    --mem={resources.mem}
    --cpus-per-task={resources.cpus_per_task}
    --job-name=smk-{rule}-%j
    --output=logs/{rule}/{rule}-%j.out
    --error=logs/{rule}/{rule}-%j.err"
default-resources:
  - time="01:00:00"
  - mem="10G"
  - cpus_per_task=1

REF_DIR: "/mnt/isilon/zhou_lab/projects/20191221_references/"
BBDUK: "/mnt/isilon/zhoulab/labsoftware/bbmap/bbduk.sh"
CONDA_ENV: "source activate_2022 Bio &&"

jobs: 100
printshellcmds: True
latency-wait: 100
reason: True
rerun-triggers: mtime
